### ISSUE TITLE
Not-an-issue: slight changes to `sway-tree-switcher`

### ISSUE THREAD

**Issue by Kabouik** [ldelossa/sway-fzfify#10]
I am really grateful that you made `sway-tree-switcher` because I was looking for some `fzf`-based script to show all my open windows across workspaces, including scratchpad, and wanted to avoid GUI so that it could integrate well with [sway-launcher-desktop](https://github.com/biont/sway-launcher-desktop).

Since your scripts are bound to Alacritty, I had to alter them a little, and took the opportunity to change a few other things in `sway-tree-switcher`. I am not submitting a PR because those are just opinionated changes and my version of the script now is bound to another terminal emulator, but perhaps those additions could be useful to others:

![ss20220909-112811](https://user-images.githubusercontent.com/7107523/189318820-f4a68dd6-0ddd-4131-bbec-3ded9017eb58.png)

Except for aesthetics and terminal changes that are just personal taste, the changes:
- hide `id` from the list of windows and remove leading spaces in window names so that they are all better aligned, 
- allow killing Wayland windows (it won't work for Xwayland windows because they have no `app_id`); killing by `id` would be much better but I haven't found how to do it,
- show up to 30 lines before vertical overflow in `fzf`,
- allow using `Tab`and `Shift+Tab` to cycle through windows (I'm assuming multiple users would bind `sway-tree-switcher` to `Alt+Tab` or something similar).

```patch
diff --git a/sway-tree-switcher b/sway-tree-switcher
index 8540455..12ef869 100755
--- a/sway-tree-switcher
+++ b/sway-tree-switcher
@@ -1 +1 @@
-#!/bin/bash
+#!/usr/bin/env bash
@@ -15,2 +14,0 @@ fi
-prompt="Windows> "
-header="Switch to which window?"
@@ -21 +19,17 @@ if [[ -n $fifo ]]; then
-    selection=$(printf $str | fzf --header=$header --prompt="$prompt" $fzf_color)
+    selection=$(printf $str \
+      | fzf --prompt="# " $fzf_color \
+            --ansi \
+	     --extended \
+	     --no-border \
+	     --layout=reverse-list \
+	     --with-nth=2.. \
+            --print-query \
+            --no-multi \
+	     --cycle \
+            --header='
+Switch (Ret) or kill (C-k)' \
+	     --margin='1,2,1,2' \
+            --color='16,gutter:-1' \
+	     --bind="tab:down" \
+	     --bind="btab:up" \
+	     --bind="ctrl-k:execute:pkill {2}")
@@ -23 +37 @@ if [[ -n $fifo ]]; then
-    id=$(echo $selection | cut -d ":" -f1)
+    id=$(echo $selection | cut -d "." -f1)
@@ -43,3 +57,2 @@ for ((i=0; i<"${#windows[@]}"; i=i+3,lines++)); do
-    name="${windows[i+2]}"
-
-    building_string="$id:"
+    name=$(echo "${windows[i+2]}" | sed 's/^ *\| *$//g')
+    building_string="$id."
@@ -48 +61 @@ for ((i=0; i<"${#windows[@]}"; i=i+3,lines++)); do
-        building_string="$building_string $app_id"
+        building_string="$building_string $app_id >"
@@ -52 +65 @@ for ((i=0; i<"${#windows[@]}"; i=i+3,lines++)); do
-        building_string="$building_string : $name"
+        building_string="$building_string $name"
@@ -65 +78,5 @@ done
-lines=$((lines+3))
+lines=$((lines+6))
+if [[ lines -gt 30 ]];
+then
+    lines=30
+fi
@@ -67 +84 @@ columns=$((columns+"${#header}"+5))
-if [[ columns -gt 100 ]];
+if [[ columns -gt 80 ]];
@@ -69 +86 @@ then
-    columns=100
+    columns=80
@@ -74,7 +91,3 @@ mkfifo $fifo
-fifo=$fifo $SHELL -c "alacritty \
-    -o window.dimensions.columns=$columns \
-    -o window.dimensions.lines=$lines \
-    -o font.size=16.0 \
-    -o window.padding.x=20 \
-    -o window.padding.y=20 \
-    --title "fzf-switcher" \
+fifo=$fifo $SHELL -c "foot \
+    -W ${columns}x${lines} \
+    -a windowswitcher \
```

I wanted to add another `fzf` keybinding to move the selected window to current workspace, but I haven't managed to find the proper `swaymsg` command to move a window by `app_id`. This is where I was:

```
# WIP: add a "Move here (C-k) command to fzf
# workspace=$(swaymsg -t get_tree | grep current_workspace | cut -d ":" -f2 | cut -d '"' -f2)
# --bind="ctrl-x:execute:swaymsg 'move [con_id={1}] to workspace $workspace'"
```
I think prepending items in the list by their workspace number would be very useful to get a quick and global view of how things are organized. The line below fetches the names of active workspaces from the Sway tree, but I failed to get the workspace number for each windows so it was broken:

```
swaymsg -t get_tree | grep num | cut -d ":" -f2 | cut -d ',' -f1
```

**Comment by ldelossa** [comment]
Cool! Other then the aesthetics things, id merge a pr that has those improvements you mention.
