### ISSUE TITLE
use swaymsg instead of sway in the commands

### ISSUE THREAD

**Issue by ecocode** [ldelossa/sway-fzfify#2]
Although calling ```sway``` to issue commands, it is better to use ```swaymsg```.

There is at least one exception which is not correctly handled when using ```sway```:  when the user uses the ```--my-next-gpu-wont-be-nvidia``` to start sway, recalling ```sway``` to issue commands needs to also contain this flag, otherwise it simple fails.

**Comment by ldelossa** [comment]
Thanks, will do this.
