### ISSUE TITLE
mention of zsh on line 75 of sway-tree-switcher

### ISSUE THREAD

**Issue by chimak111** [ldelossa/sway-fzfify#4]
Shouldn't line 75 in sway-tree-switcher `fifo=$fifo zsh -c "alacritty \` have `sh` or `bash` instead of `zsh`?

**Comment by ldelossa** [comment]
@chimak111 

You're right, these scripts were ripped out of my personal .config so this is a lay over from that. If you'd like to send a PR feel free, if not I can fix this in a bit.

**Comment by ldelossa** [comment]
hey @chimak111 I made all the scripts use the $SHELL variable which I think is provided by most shells which adhere to POSIX-ish things.
